### ISSUE TITLE
Create Endpoint Documentation

### ISSUE THREAD

**Issue by GreysonElkins** [HireUp-Turing/HireUp_backend#23]
- [x] Add the following Endpoints to BE's readme
**note:** `Phases` correlate to FE's plan to implement, if building these endpoints in a different order makes more sense, go for it! 
#### Phase 1: Employers search and view users
- [x] All users (as an array, see FE-11 for what data we're looking for) 
  * doesn't need messages
  * allows us to test connectivity easily before designing intense logic
  * load all users to design search-results page (and applicantPreview components)
- [x] search endpoint (search => searchResults)
  * Query params or body info? 
  * doesn't need messages
  * allows us to test connectivity easily before designing intense logic
  * load all users to design search-results page (and applicantPreview components)
- [x] applicant search-options (search component onMount)
  * Returns an object with `skills` and `values` arrays
  * arrays include all attributes present on user profiles
#### Phase 2: User creation 
- [x] Single user (myAccount (in demo, after account has been created)
  * for "my account", 
    * #11 with personal info too 
    *`assuming auth`, find by username or email, returns everything in a profile
  * or for when you click a search result, although we may not need that
- [x] post new users (myAccount => create user form (post) => my profile page)
  * This will be triggered at the start of clicking "My Profile" in demo mode
- [x] post changes to a single user (myAccount => edit) *extension*
  * Allows a user to edit their own profile 
  * Since they're logged in, they can use the ID
#### Phase 3: Messaging Users
- [x] all messages belonging to user by `id`
  * (may not be necessary given the `Single User` path)
- [x] post new message
  * Any user can do this, contains the id of the applicant receiving the message
